accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),

]

articles/urls.py
from django.urls import path, include
from . import views


app_name = "articles"
urlpatterns = [
    path('', views.home, name="home"),
    path('right/', views.right, name="right"),
    path('left/', views.left, name="left"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
	pass

articles/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Subject(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
        return self.title

class Head(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    poster_path = models.CharField(max_length=500)

    def __str__(self):
        return self.title

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    head = models.ForeignKey(Head, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Community(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    head = models.ForeignKey(Head, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from myapp.models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:home')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST' :
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('articles:home')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }

    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        # auth_logout(request)
    return redirect('articles:home')
    

articles/views.py
from django.shortcuts import render, redirect
from .models import Head, Comment, Community

# Create your views here.
def home(request):
    heads = Head.objects.all()
    comments = Comment.objects.all()
    
    # print(heads)
    context ={
        'heads': heads,
        'comments': comments,
    }
    return render(request, 'articles/home.html', context)

def right(request):
    communities = Community.objects.all()
    context = {
        'communities': communities,
    }
    return render(request, 'articles/right.html', context)

def left(request):
    return render(request, 'articles/left.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'accounts:login' %}" method='POST'> 
{% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>

  <form action="{% url 'accounts:signup' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock  %}

articles/templates/articles/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h1>home</h1>
{% for head in heads %}
  {{ head.title }} 

  <div class="container">
    <img src="{% static 'images/nct1.jpeg' %}" class="rounded float-start" alt="nct">
    <a class="btn btn-primary" href="{% url 'articles:left' %}" role="button">nct</a>
    {% for comment in comments %}
      {% if comment.head.pk == head.pk %}
        <p>{{ comment.content }}</p>
      {% endif %}
    {% endfor %}
  </div>

{% endfor %}

<div class="container">
  <h1>vs</h1>
</div>

<div class="container">
  <img src="{% static 'images/세븐틴1.jpeg'  %}" class="rounded float-end" alt="세븐틴">
  <a class="btn btn-primary" href="{% url 'articles:right' %}" role="button">세븐틴</a>
</div>

{% endblock  %}

articles/templates/articles/left.html
{% extends 'base.html' %}

{% block content %}
<h1>NCT</h1>

{% endblock %}

articles/templates/articles/right.html
{% extends 'base.html' %}

{% block content %}

<h1>세븐틴</h1>
{{communities}}

  {% for community in communities %}
    {% comment %} <a href="#"> {% endcomment %}
    {{ community.title }}
    {% comment %} </a> {% endcomment %}
    <hr>
  {% endfor %}

{% endblock  %}

templates/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>Base</title>
</head>
<body>
  {% include 'navbar.html' %}
  <h2>안녕하세요 {{user}}</h2>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  
  {% bootstrap_javascript %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'articles:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">CREATE</a>
        </li>
        {% if user.is_authenticated == False %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        {% endif %}
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            회원정보
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:delete' %}">탈퇴하기</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>